### PR TITLE
add babel-preset-modern-browsers

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@askmatey is this project still alive?

**Comment by askmatey** [comment]
Can you squash Christophe Hurpeau's commits, please (something like `merge-babel-preset-modern-browsers`)

**Comment by graingert** [comment]
@askmatey ok, but I put a lot of effort in to maintain the history here.

**Comment by timoxley** [comment]
bump

**Comment by graingert** [comment]
@askmatey rebased. FYI: You can "merge with squashes" from the GitHub UI

**Pull request merged**
